module.exports = {
  rack: {
    table: "rack",
    columns: {
      id: "id",
      name: "name",
      location: "location",
    },
  },

  physical: {
    table: "physicalServer",
    columns: {
      id: "id",
      name: "name",
      ip: "ip",
      owner: "owner",
      year: "year",
      status: "status",
      cpu: "cpu",
      ram: "ram",
      storage: "storage",
      detail: "detail",
      image: "image",
      rackId: "rackId",
      authUsername: "authUsername",
      authPassword: "authPassword",
      ownerContact: "ownerContact",
      createdAt: "createdAt",
      updatedAt: "updatedAt",
      category: "category",
    },
  },
  host: {
    table: "host",
    columns: {
      id: "id",
      ip: "ip",
      version: "version",
      serverDevice: "serverDevice",
      status: "status",
      detail: "detail",
      physicalId: "physicalId",
      name: "name",
      authUsername: "authUsername",
      authPassword: "authPassword",
      createdAt: "createdAt",
      updatedAt: "updatedAt",
      category: "category",
    },
  },
  guest: {
    table: "guest",
    columns: {
      id: "id",
      name: "name",
      ip: "ip",
      owner: "owner",
      domainInstance: "domainInstance",
      ram: "ram",
      storage: "storage",
      cpu: "cpu",
      model: "model",
      osVersion: "osVersion",
      status: "status",
      detail: "detail",
      hostId: "hostId",
      authUsername: "authUsername",
      authPassword: "authPassword",
      createdAt: "createdAt",
      updatedAt: "updatedAt",
      category: "category",
    },
  },

  accessPoint: {
    table: "accessPoint",
    columns: {
      id: "id",
      name: "name",
      ip: "ip",
      type: "type",
      category: "category",
      tahunAnggaran: "tahunAnggaran",
      location: "location",
      locationDetail: "locationDetail",
      mac: "mac",
      controllerAP: "controllerAP",
      code: "code",
      createdAt: "createdAt",
      updatedAt: "updatedAt",
    },
  },
  switch: {
    table: "switch",
    columns: {
      id: "id",
      name: "name",
      ip: "ip",
      type: "type",
      location: "location",
      locationDetail: "locationDetail",
      status: "status",
      code: "code",
      createdAt: "createdAt",
      updatedAt: "updatedAt",
      category: "category",
      detail: "detail",
    },
  },
  router: {
    table: "router",
    columns: {
      id: "id",
      name: "name",
      ip: "ip",
      type: "type",
      location: "location",
      locationDetail: "locationDetail",
      status: "status",
      detail: "detail",
      code: "code",
      createdAt: "createdAt",
      updatedAt: "updatedAt",
      category: "category",
    },
  },
  cctv: {
    table: "cctv",
    columns: {
      id: "id",
      name: "name",
      ip: "ip",
      location: "location",
      locationDetail: "locationDetail",
      type: "type",
      status: "status",
      detail: "detail",
      code: "code",
      createdAt: "createdAt",
      updatedAt: "updatedAt",
      category: "category",
    },
  },
};
